CLASS LHC_ZR_RENT_CUSTOM_JPJCP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrRentCustomJpjcp
        RESULT result.
ENDCLASS.

CLASS LHC_ZR_RENT_CUSTOM_JPJCP IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
